### ISSUE TITLE
Can I construct my own request for testing?

### ISSUE THREAD

**Issue by vivekpatani** [symphonyoss/hubot-symphony#66]
My Hubot (Gifbot) is working all right. Is there a way for me to send a self constructed request (via postman or some cURL request) to the coffee script? If yes, please can someone guide me?

**Comment by jonfreedman** [comment]
It's not clear what the purpose and content of your request would be, if you want to send something to the bot for it to process and act upon by sending a message or something similar that's known as a webhook.  You can find more details [here](https://hubot.github.com/docs/scripting/#http-listener).

There's a limit to what you can easily do in response to a message, hopefully the necessary functionality is either available via hubot itself e.g. sending a simple message, otherwise you can any of the methods exposed in the [Adaptor](https://github.com/symphonyoss/hubot-symphony/blob/master/src/adapter.js) such as sendDirectMessageToEmail as shown [here](https://github.com/symphonyoss/hubot-symphony#non-standard-messaging).
